services:
  historialmedico:
    build:
      context: .
    container_name: historialmedico
    ports:
      - "8089:8089"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/historialMedicoDB
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # Asegurar persistencia opcional
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
